# Generated by Django 5.1.2 on 2025-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
