# Generated by Django 5.1.2 on 2025-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clubs_courses_events_enrollments_eventregistrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
