# Generated by Django 5.1.2 on 2025-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_club_id_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='club_id',
        ),
        migrations.AlterField(
            model_name='eventregistrations',
            name='event_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
