# Generated by Django 5.1.2 on 2025-08-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_events_club_id_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrations',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
