# Generated by Django 5.1.2 on 2025-08-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_eventregistrations_event_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistrations',
        ),
    ]
